### ISSUE TITLE
Consider moving to having all outputs go to single folder

### ISSUE THREAD

**Issue by aeturrell** [aeturrell/cookiecutter-research-project#4]
Project level yml would be, eg, 

```yaml
project:
  execute-dir: project
  output-dir: outputs
```
